---

- hosts: localhost
  connection: local

  vars: 
    fruits: 
      - Apple
      - Ornage
      - banana
      - grapes
  tasks: 
   - command: echo "{{ item }}"
     with_items: '{{ fruits }}'

   - debug: msg="{{ item }}"
     with_items: '{{ fruits }}'
