---

- hosts: web 
  become: true
  vars:
    users:
    -  "paul"
    - "tanya"
    - "ruby"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
    with_items: "{{ users }}"
  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item }}" 
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    with_items: "{{ users }}"
    register: var_tmp

  - name: debugging
    debug: var=var_tmp
