---
- hosts: "New"
  vars:
    users:
    -  "paul"
    - "tanya"
    - "ruby"
  tasks:
  - name: "Create user accounts"
    user:
      name: "{{ item }}"
    with_items: "{{ users }}"
    become: yes

  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file',  '/home/ec2-user/.ssh/id_rsa.pub') }}"
    with_items: "{{ users }}"
    become: yes

